#!/bin/bash
#For USB interface cable, the test does not function with larger files e.g. test5.txt  

file=test1.txt 

./com2_cntrl.sh DISABLE

echo " Attach RS485 cable "
echo " Press any key to continue "
read -n 1

./set_serial.sh RS485 RELAY /dev/ttyS0
source ./baudtest.sh /dev/ttyS1 RS485 $file

#EOF

